description: >- 
  This project provides debian packages for sg200x based boards.
baseurl: "/sophgo-sg200x-aptrepo"
url: "https://sg200x.deb.git.pnxlr.eu.org"
github_username: Pairman

# Build settings
theme: minima
exclude:
  - tools/
  - doc/