description: >- 
  This project provides debian packages for sg200x based boards.
baseurl: "/sophgo-sg200x-aptrepo"
url: "https://pairman.github.io"
github_username: Pairman

# Build settings
theme: minima
exclude:
  - tools/
  - doc/